Made class attributes to be a list
DroneBase/ml-dronebase-data-utils pull request #44
Opened 2022-09-12 05:15 UTC by agrawalsourav98

Made class attributes parameter in `convert_geojson.py` to be a list to allow use of geojsons which have different feature columns representing class.

Use Case, The latest labelling has`class`, `Class`  and `id` all representing the class of a defect.

2022-09-12 13:22 UTC, isaaccorley requested changes

2022-09-12 13:22 UTC, isaaccorley commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +            if not len(names):
Is this indented properly?

2022-09-12 13:22 UTC, isaaccorley commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +            for attr in class_attribute:
This for loop can be replaced with something like:

if not all([True if gdf.get(attr) else False for attr in class_attributes]):
   raise ValueError(...)

Try/except is not a good solution in this case.

2022-09-12 13:28 UTC, agrawalsourav98 commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +            for attr in class_attribute:
Okay, the main idea is to find the attribute from the list which applies to the current gdf objejct. I will replace try/catch with something like a for loop which checks which one matches and use that instead.

2022-09-12 18:43 UTC, isaaccorley requested changes

2022-09-12 18:43 UTC, isaaccorley commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +                names = gdf.get(attr, [])
Can you explain what the goal of this for loop is? It's not clear to me why you are defaulting gdf.get to return an empty list when it naturally defaults to None. Are you just checking to make sure the class attributes are valid classes that user defines in the CLI call?

2022-09-13 06:14 UTC, agrawalsourav98 commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +                names = gdf.get(attr, [])
So, the for loop is for handling multiple class attributes. Say, you have 100 geojsons and they have the defect class represented by attributes `A`, `B` and `C`, so the for loop would check which attribute is present in the particular geojson and uses that to get the classes from a particular geojson.
If either of the three is not found if errors out, so the user can ideally add it and then re-run the tool.

2022-09-13 06:16 UTC, agrawalsourav98 commented on ml_dronebase_data_utils/geo/convert_geojson.py
> +                names = gdf.get(attr, [])
For the empty list thing, I have only added it to represent the list of classes were not found using the given attribute.

2022-09-14 04:05 UTC, merged