Added bbox representation and conversion
DroneBase/ml-dronebase-data-utils pull request #46
Opened 2022-10-21 20:19 UTC by conor-wallace

This PR adopts detectron2's bbox mode representation and expands it for our use which includes yolo, voc, rotated voc, rotated coco and more box modes. It also adds a bbox georeferencing function. I also incremented the minor version because the new box modes represent a fairly large divergence in work flow.

2022-10-21 20:33 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +class BoxMode(IntEnum):
This is adopted from detectron2. Their version mainly supports voc/coco style bboxes so this version adds more support for voc/coco rotated bboxes as well as yolo/albumentations style bboxes.

2022-10-21 20:33 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +    XYWH_ABS = 1
COCO style bbox

2022-10-21 20:34 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +    XYXY_REL = 2
YOLO style bbox

2022-10-21 20:34 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +    XYWH_REL = 3
YOLO style bbox

2022-10-21 20:35 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +    XYXYA_ABS = 4
VOC style rotated bbox

2022-10-21 20:35 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +    XYWHA_ABS = 5
COCO style rotated bbox

2022-10-21 20:36 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_mode.py
> +        # if xyxy to xywh
There are three main conversions that happen which are captured in this logic:
- VOC to COCO conversion
- COCO to VOC conversion
- Absolute to Relative conversion

2022-10-21 20:37 UTC, conor-wallace commented on ml_dronebase_data_utils/bbox/box_utils.py
> +from .box_mode import BoxMode
Applied new ```BoxMode``` throughout the repository where necessary.

2022-10-21 20:39 UTC, conor-wallace commented on ml_dronebase_data_utils/geo/geo_utils.py
> +def georeference_boxes(image_path: str, boxes: np.ndarray) -> List[Any]:
This was simply copied from the solar panel detection repo and cleaned up a bit. It takes in a ```Nx4x2``` array of bounding box vertices in image coordinates and the path/url to a georeferenced image and returns a ```Nx4x2``` array of bounding box vertices in geo coordinates.

2022-10-21 20:45 UTC, conor-wallace commented on ml_dronebase_data_utils/geo/geo_utils.py
> +def georeference_boxes(image_path: str, boxes: np.ndarray) -> List[Any]:
I'm not sure if it would make it better or worse to make this function more generalized by returning an ```Nx4x2``` array back to match the input boxes and just return the georeferenced boxes, but the use for this for now is to take the output and write it to a geojson file which expects polygons.

2022-10-21 20:46 UTC, conor-wallace commented on ml_dronebase_data_utils/voc/parse_voc.py
> +def parse_voc_xml(
The user can now parse VOC files and directly get back the boxes in whichever ```BoxMode``` they want, e.g., directly reading in YOLO-style bboxes from the xml file.

2022-10-21 20:47 UTC, conor-wallace commented on setup.cfg
>  [options.extras_require]
I simply alphabetized the dependencies to make it more readable and to try to help prevent adding duplicate dependencies in the future.

2022-10-21 20:48 UTC, conor-wallace commented on tests/conftest.py
> +def get_box_conversion_test_params():
This tests all possible conversions between boxes. This test could be made more robust by also testing invalid combinations of arguments, but it seemed fine for now.

2022-10-24 21:17 UTC, isaaccorley requested changes
lgtm just need to update `setup.cfg` `voc` dependencies

2022-10-24 21:17 UTC, isaaccorley commented on setup.cfg
>  voc =
You need to change voc deps as well now because you import `bbox.box_mode.py` in `voc/parse_voc.py`

2022-10-24 21:21 UTC, isaaccorley approved these changes

2022-10-24 21:26 UTC, merged