Added missing requirements
DroneBase/ml-dronebase-data-utils pull request #48
Opened 2022-11-07 11:17 UTC by agrawalsourav98

2022-11-07 16:01 UTC, isaaccorley requested changes
These deps should be added to the geo section of setup.cfg not voc.

2022-11-08 05:10 UTC, agrawalsourav98 commented
> These deps should be added to the geo section of setup.cfg not voc.

The issue is only with the voc section. If you install using `ml-dronbase-data-utils[voc]` you would get import error when using the voc code.

2022-11-08 06:02 UTC, agrawalsourav98 commented on setup.cfg
>      numpy
Added

2022-11-09 14:33 UTC, isaaccorley commented
> > These deps should be added to the geo section of setup.cfg not voc.
> 
> 
> 
> The issue is only with the voc section. If you install using `ml-dronebase-data-utils[voc]` you would get import error when using the voc code.

I traced this and it's actually because parse_voc imports bbox so it requires all deps from bbox.

2022-11-09 14:34 UTC, isaaccorley approved these changes

2022-11-09 15:09 UTC, merged