Use separate sessions in boto3 requests
DroneBase/ml-dronebase-data-utils pull request #51
Opened 2023-03-12 07:07 UTC by agrawalsourav98

Use separate sessions for boto3 requests instead of the default session to ensure threadsafety across s3 operations. This allows to ues multithreaded s3 operations downstream.

2023-03-13 03:56 UTC, agrawalsourav98 commented
All the class parameter changes to `None` are related to `B006` flake8 error from the [flake8-bugbear](https://pypi.org/project/flake8-bugbear/) extension.
```
B006: Do not use mutable data structures for argument defaults. They are created during function definition time.
All calls to the function reuse this one instance of that data structure, persisting changes between them.
```
The above changes are a better way to represent the same logic.

2023-03-13 22:19 UTC, isaaccorley commented
I will wait for Conor's review on this so he's aware of the changes to the classes args since I believe it's used in some detection code elsewhere.

2023-03-22 23:54 UTC, isaaccorley requested changes
Can you make sure the tests cover these so we can verify that the changes works?

2023-03-22 23:54 UTC, isaaccorley commented on ml_dronebase_data_utils/s3/s3.py
> +def chunk(it: Iterable, size: int) -> Iterator:
Is there not one of our libraries that already implements this?

2023-03-28 06:59 UTC, agrawalsourav98 commented on tests/test_s3.py
Add test cases to test all the s3 functions.

2023-03-28 13:09 UTC, isaaccorley commented on ml_dronebase_data_utils/s3/s3.py
> +def chunk(it: Iterable, size: int) -> Iterator:
I was thinking itertools might have this but maybe it doesn't.

2023-03-28 13:16 UTC, isaaccorley approved these changes
Looks great!

2023-03-28 13:44 UTC, merged